_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 55
                - 105
            "2":
                - 55
                - 105
            "3":
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
